### ISSUE TITLE
False call in plotting example

### ISSUE THREAD

**Issue by jkbgbr** [pyansys/pydpf-core#113]
The example provided for [plotting](https://dpfdocs.pyansys.com/user_guide/plotting.html) throws an AttributeError as in the example showing how to visualize strains the call

`strain = model.results.strain()`

should be 

`strain = model.results.elastic_strain()`

**Comment by cbellot000** [comment]
Thanks for reporting this issue @jkbgbr, it will be fixed by the linked Pull Request
