### ISSUE TITLE
DPFServerException using Docker 

### ISSUE THREAD

**Issue by Amrit-Hub** [pyansys/pydpf-core#142]
I am running pydpf-core using docker.( I do not have Ansys 2021 but have Ansys 2020 R2)
Here is what I have done so far:
1. Authorized Docker to access the repository using cat GH_TOKEN.txt | docker login docker.pkg.github.com -u $GH_USERNAME --password-stdin. It is successful
2. This gave me error "the input device is not a TTY." for 
docker run -it --rm -v `pwd`:/dpf -p 50054:50054 docker.pkg.github.com/pyansys/dpf-core/dpf:v2021.1
3. So I used the following command and docker container was running successfully.
winpty docker run -it --rm -v `pwd`:/dpf -p 50054:50054 docker.pkg.github.com/pyansys/dpf-core/dpf:v2021.1
4. In notebook, i used this and it connected to server properly
from ansys.dpf import core as dpf_core
dpf_core.connect_to_server()
5. But I am getting error "DPFServerException: missing UpdateRequest::InputCase:: enum " whenever I run
from ansys.dpf.core import Model
from ansys.dpf.core import examples
model = Model(examples.simple_bar)
print(model)
6. Also this error "_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:" whenever I run
from ansys.dpf import core as dpf
from ansys.dpf.core import examples
path = examples.simple_bar
model = dpf.Model(path)

Consider me as new to this. Please help to troubleshoot using Docker

**Comment by Amrit-Hub** [comment]
I am using windows system, vscode, docker for desktop, git for windows to start docker.

**Comment by rlagha** [comment]
Hello @Amrit-Hub , thanks for the detailed issue description, if you can have access to the 2021R2, this will be great, otherwise please could you contact us into pyansys.support@ansys.com, then we can work for a solution to provide an updated docker?

Regards
Ramdane Lagha

**Comment by Amrit-Hub** [comment]
Hi @rlagha, apologies for delay. I have send the full details of the steps and errors via email. Please do the needful.
