### ISSUE TITLE
What is wrong in this simple code?

### ISSUE THREAD

**Issue by jlcuadros** [pyansys/pydpf-core#143]
Hello everybody

Please I hope you can help me to understand this

```python
from ansys.dpf import core as dpf
my_field_1 =dpf.Field(4, dpf.natures.scalar)
my_data_1 = [1,2,3,4]
my_field_1.data=my_data_1

op = dpf.operators.math.accumulate()
op.inputs.fieldA.connect(my_field_1)
my_field = op.outputs.field()
my_field.data
```
**why my_field.data equals to [0] in stead of [10]**

Thank you in advance and best regards

Jose Luis

**Comment by rlagha** [comment]
Hi @jlcuadros,
This is in fact confusing, We need to inform the user when the data is not assigned to the field. Your syntax is good we will try to get it working as you wrote it.
In fact the field, as it's defined, is always data associated to entities; this way when you get for example a field of nodal displacement you can know for each x,yz in the data array, at which node id it's associated with. Thus we create a field we always have data and a scoping:
in your case you can do it this way:
```
my_field_1 =dpf.Field(4, dpf.natures.scalar)
for i in range (1,5) :
    my_field_1.append([i],i)
op = dpf.operators.math.accumulate()
op.inputs.fieldA.connect(my_field_1)
my_field = op.outputs.field()
my_field.data
```

Regards
Ramdane

**Comment by jlcuadros** [comment]
Thank you very much @rlagha 

Best regards

Jose Luis

**Comment by mcMunich** [comment]
@rlagha  The script in question is from an Ansys Learning Hub pydpf training.

**Comment by jlcuadros** [comment]
thanks
