### ISSUE TITLE
why don't my dpf core elastic strain results match my ansys mechanical results?

### ISSUE THREAD

**Issue by mcMunich** [pyansys/pydpf-core#154]
hello, trying to match some ansys mechanical results and I am pretty sure it is some detail I am not aware of.
I have a simple model in mechanical that is solved and the .rst written to file. The equivalent stress and strain are calculated as expected. 

The equivalent strain is equivalent stress/E modulus:
![image](https://user-images.githubusercontent.com/84008975/147648023-cef04b83-9118-4bf7-bb31-e7c0db496b01.png)
In my dpf core instance, I get the same values for equivalent stress:
![image](https://user-images.githubusercontent.com/84008975/147648124-91467830-89f9-4b7c-afe7-912b87673255.png)
But when I generate a strain I can't match my mechanical results (and I think I tried all the available). 
![image](https://user-images.githubusercontent.com/84008975/147648250-d95c0289-b29e-42b6-b857-1915c1f7c698.png)

Is there some averaging or nodal calculation going that I am missing?
I would like to be able to match a mechanical generated strain with a dpf post processed result.

**Comment by rlagha** [comment]
Hi @mcMunich ,
May I ask you to compare normal and shear strains? I suspect an issue on NUXY. 
Thanks
Ramdane

**Comment by mcMunich** [comment]
hey Ramdane, the elastic_strain_X,Y,Z do agree with the mechanical result.

**Comment by rlagha** [comment]
@mcMunich , please could you try this?
```
strain = model.results.elastic_strain()
strain.inputs.requested_location.connect(dpf.locations.nodal)
eqv = dpf.operators.invariant.von_mises_eqv_fc(fields_container=strain.outputs.fields_container)
model.metadata.meshed_region.plot(eqv.eval())
```

Thanks
Ramdane

**Comment by mcMunich** [comment]
@rlagha That works. The eqv equals the mechanical equivalent elastic strain - Averaged. 
invariant? wasn't on my radar.

**Comment by rlagha** [comment]
@mcMunich  yes, we classified the equivalent von mises as an inviariant quantity since it's derived from the eigen values of the stress or strain tensors. The issue with strain eqv, is that it needs the NUXY, thus I recommend to request the trsain split by body/material, when it's a multi body/material model.
`strain = model.results.elastic_strain.split_by_body()`

Thanks
Ramdane
