### ISSUE TITLE
operators.invariant.eigen_vectors and operators.invariant.eigen_vectors_fc don't make sense

### ISSUE THREAD

**Issue by smedleydowell** [pyansys/pydpf-core#155]
It seems the eigen_vectors and eigen_vectors_fc operators are "mixed up" and not consistent with the usage of the other operators in the invariant package.  

Documentation says the eigen_vectors operator has fields as input and fields_container as output:
![image](https://user-images.githubusercontent.com/65084033/147769581-e134fbad-d707-4e85-b21d-2456c300704a.png)

Documentation says the eigen_vectors_fc operator takes a single field as input and output.  
![image](https://user-images.githubusercontent.com/65084033/147769853-eda24370-9788-4fe2-b0be-bf99d53e9047.png)

This is not consistent with other invariant operators.  Further, when trying to execute code using the documented examples, it raises an error that I cannot resolve (maybe due to lack of my understanding, or maybe there is a bug).

Example code:
![image](https://user-images.githubusercontent.com/65084033/147772215-ea6d9234-d6cd-42b7-b3b6-6287b6a6bbc8.png)

**Comment by rlagha** [comment]
@smedleydowell, yes unfortunately the documentation and the generated code are wrong for this operator, we will fix this soon.
meanwhile please could you try using it this way?
```
eig_vec_op = dpf.operators.invariant.eigen_vectors_fc()
eig_vec_op.connect(0,s_op,0)
fields = eig_vec_op.get_output(0, dpf.types.fields_container)
field = fields[0]
```
Regards
Ramdane

**Comment by smedleydowell** [comment]
@rlagha : The work-around you proposed works very well for me.  I would never have found this way of doing it.. thanks for your help!!

Regards,
 Jack
