### ISSUE TITLE
dpf.operators.mesh.node_coordinates() doesn't work

### ISSUE THREAD

**Issue by Tombock17** [pyansys/pydpf-core#157]
Hello,

I'm trying to extrapolate the coordinates of the nodes of my mesh, using:

op = dpf.operators.mesh.node_coordinates()
op.inputs.mesh.connect(my_mesh)
result_coordinates = op.outputs.coordinates()

But I have this output:
result_coordinates = op.outputs.coordinates()
AttributeError: 'OutputsNodeCoordinates' object has no attribute 'coordinates'

Can you help me? 
Thanks

**Comment by rlagha** [comment]
@Tombock17 do you want to extract the nodes coordinates of the mesh as a field? What do you mean by extrapolate?

**Comment by Tombock17** [comment]
@rlagha Thanks for your time.

I need to have the coordinates of the nodes. The mesh is read from the file .rst

My aim is to plot only some nodes with a specific values, like the example "Plot results on a specific path".
I understood that I need the coordinates of the nodes, so I can do the same of the example, but I cannot arrive at these.
It seems that there is something wrong in the operator node_coordinates(). Is it right?

**Comment by Tombock17** [comment]
I found an alternative way:
node = r.metadata.meshed_region.nodes[0]
node.coordinates

In this way I can read the coordinates of the node.
The other code lines that I wrote, I'm quite sure that doesn't work and I found these here https://dpfdocs.pyansys.com/api/ansys.dpf.core.operators.mesh.node_coordinates.html?highlight=coordinates#module-ansys.dpf.core.operators.mesh.node_coordinates

Sorry for the waste of time and thanks.
