### ISSUE TITLE
Memory allocation issue 

### ISSUE THREAD

**Issue by Tombock17** [pyansys/pydpf-core#161]
Hi guys,

We read a file .rst and we want read elastic strain, plastic strain, seqv and temperature for each nodes of all the components that are defined (for every time steps)
We save all this data in some dictionaries, that we need for the following functions.
An example of dictionary:
M_elastic={‘comp1’:[elastic strain for each node at every times]; ‘comp2’:[elastic strain for each node at every times]; ‘comp3’:[elastic strain for each node at every times];…}

It works very well if we use a file .rst with a limited size (5GB), but if we use a larger file .rst (20GB) the program analyzed 6-7 components approximately and after he dies, showing the following error:
<img width="300" alt="DPFerror" src="https://user-images.githubusercontent.com/97595967/150783952-7e109966-1d41-4f9a-9fe7-883241195c10.png">
(sorry for the quality of the figure)

We thought that it was a problem regarding the memory, but if we analyze all the nodes, without considering the components (so we are analyzing more nodes than the previously case), all the program work very well and very fast too.
In the file .rst we have 200k nodes, 55 components, 45 time steps.

I think that file .rst is not important, what it is important are its sizes, maybe the number of components and the number of time steps.
I mean, this is only a case, what happen if I try to read a file .rst with a bigger size? Are dpf core depended by the sizes of the rst?
If it is, how can I estimate the bigger size that I can read? And How can I read file with a bigger size? With mapdl library?

I hope that you can help me to understand better.
Thanks and regards,
Tommaso

here a part of my code:
     r=Model(file)
     data_sources=dpf.DataSources(file)
     tf = r.metadata.time_freq_support
     tf_array=tf.time_frequencies.data
     tf_list=list(tf_array)
     comp=r.metadata.available_named_selections
     matrix_dpf_seqv=dict()
     matrix_dpf_e=dict()
     matrix_dpf_p=dict()
     matrix_dpf_T=dict()
     matrix_dpf_nodes=dict()
     for s in range (0,len(comp)):
            q=dpf.mesh_scoping_factory.named_selection_scoping(comp[s],r)
            
            # ELASTIC STRAIN
            estrainop = dpf.operators.result.elastic_strain()
            estrainop.inputs.data_sources.connect(data_sources)
            estrainop.inputs.mesh_scoping.connect(q)
            estrainop.inputs.time_scoping.connect(tf_list)
            estrainop.inputs.requested_location('Nodal')
            e_strain_comp = estrainop.outputs.fields_container()
            
            # PLASTIC STRAIN
            # Agire qui se l'analisi non è presente
            pstrainop = dpf.operators.result.plastic_strain()
            pstrainop.inputs.data_sources.connect(data_sources)
            pstrainop.inputs.mesh_scoping.connect(q)
            pstrainop.inputs.time_scoping.connect(tf_list)
            pstrainop.inputs.requested_location('Nodal')
            p_strain_comp = pstrainop.outputs.fields_container()
            
            # SEQV
            seqvop = dpf.operators.result.stress_von_mises()
            seqvop.inputs.data_sources.connect(data_sources)
            seqvop.inputs.mesh_scoping.connect(q)
            seqvop.inputs.time_scoping.connect(tf_list)
            seqvop.inputs.requested_location('Nodal')
            seqv_comp = seqvop.outputs.fields_container()
            
            # TEMPERATURE
            top = dpf.operators.result.structural_temperature()
            top.inputs.data_sources.connect(data_sources)
            top.inputs.mesh_scoping.connect(q)
            top.inputs.time_scoping.connect(tf_list)
            top.inputs.requested_location('Nodal')
            t_comp = top.outputs.fields_container()
            
            list_nodes=seqv_comp[0].scoping.ids
            stress=[]
            elast=[]
            plast=[]
            temp=[]
            for t in range (0,len(tf_array)):
                stress.append(seqv_comp[t].data)
                elast.append(e_strain_comp[t].data)
                if len(p_strain_comp[t].data)>0:
                    plast.append(p_strain_comp[t].data)
                else:
                    p_temp=np.zeros(len(p_strain_comp[t].data),len(p_strain_comp[t].data[0]))
                    plast.append(p_temp)
                temp.append(t_comp[t].data)     
            matrix_dpf_seqv[comp[s]]=stress
            matrix_dpf_e[comp[s]]=elast
            matrix_dpf_p[comp[s]]=plast
            matrix_dpf_T[comp[s]]=temp
            matrix_dpf_nodes[comp[s]]=list_nodes

**Comment by dpfbuild** [comment]
Hi @Tombock17 , yes in dpf you can read any size of rst file.
please could you connect the streams to the operators instead of connecting the data sources like in the line bellow?
```
estrainop.inputs.streams_container.connect(model.metadata.streams_provider.outputs.streams_container)
```
This will be faster and avoid reading the cached meta data in each file.

Please let me know if this help or we can investigate more.

Regards
Ramdane

**Comment by Tombock17** [comment]
Thanks Ramdane! Good advice!
Now it works a little faster. But we have the same issue:
<img width="421" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/97595967/151008779-53d2b3c9-2bc2-42ef-ad95-566507edfc0e.png">

For the moment I fixed it in this way: I delete all the operators and their output at the end of each iteration. I was quite sure that every iteration the operator was overwrite, but maybe I was wrong.

However I hope that it is only temporary solution, because the action to delete the operators and their output is slow, and I loose a lot of time in the end of the program.

So, do you have other ideas?

Thanks for your time.
Regards,
Tommaso

**Comment by dpfbuild** [comment]
@Tombock17 you are welcome.
I think that this is a garbage collector issue.
Could you re-write your code this way?
Do the first instantiation, the connections and the evaluation of your operators for the first component outside of the loop, like bellow:
```
estrainop = dpf.operators.result.elastic_strain()
estrainop.inputs.streams_container.connect(M.metadata.streams_provider.outputs.streams_container)
estrainop.inputs.mesh_scoping.connect(q)
estrainop.inputs.time_scoping.connect(tf_list)
estrainop.inputs.requested_location('Nodal')
e_strain_comp = estrainop.outputs.fields_container()
```

And then in your loop re-use the same operators and only connect the i'th component and re-inject the fields container to avoid reallocating the memory. In your loop you will only have for each result:
```
estrainop.inputs.mesh_scoping.connect(q)
estrainop.inputs.fields_container.connect(e_strain_comp)
e_strain_comp = estrainop.outputs.fields_container()
```
Please let me know if this helps.

Regards
Ramdane

**Comment by Tombock17** [comment]
Hi Ramdane,

In this way we haven't the memory allocation issue, but the time of execution is higher than the last version (that it was about 2 hours). So do you have some other ideas? In alternative, I think that we continue to delete the operators every iteration, can it create some issue in other case of analysis?

In addition the memory is always very close to the 100% (with the new modify that you suggest)
<img width="412" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/97595967/151150342-2bed2698-8983-4cdc-8133-0011ef5acbfa.png">
What happen if I try this script in a machine with a lower RAM? Does the memory adapt to a lower RAM or it crash?

Regards,
Tommaso

**Comment by rlagha** [comment]
Hi @Tombock17 ,
Then this is strange... if you can attach your script here or send it to pyansys.support@ansys.com, I'll have a look and try to understand.
There is no issue with your workaround.
If there is no enough RAM, then you will get the same message as you showed -- memory allocation issue-- but this should not crash your system.

Regards
Ramdane
