### ISSUE TITLE
TimeoutError: Server did not start in 10 seconds

### ISSUE THREAD

**Issue by settyakshay** [pyansys/pydpf-core#164]
Hi,
I am trying to read the rst file with following commands:
from ansys.dpf import core as dpf
my_data_sources= dpf.DataSources()
my_data_sources.set_result_file_path("C:/Users/amd8kor/Desktop/ANSYS_DPF/WS031_file.rst")

I have installed the pip packages but not able to read the rst file as I am getting the following error : 

File "C:\Users\amd8kor\.conda\envs\py37\lib\site-packages\ansys\dpf\core\server.py", line 538, in launch_dpf
    raise TimeoutError(f"Server did not start in {timeout} seconds")
TimeoutError: Server did not start in 10 seconds

I even tried to connect to dpf server with following command but I am getting the same error:
>>> from ansys.dpf import core as dpf
>>> dpf.connect_to_server(ip='10.0.0.22', port=50054)

Is there a work around for this problem? Thanks in advance

Regards,
Akshay

**Comment by rlagha** [comment]
hi @settyakshay , please could you tell me what is the version of pyDPF that you are using (pip show ansys.dpf.core) and what is the version of the Ansys workbench that you installed?
Thanks
Ramdane

**Comment by settyakshay** [comment]
Hi..
Name: ansys-dpf-core
Version: 0.3.4

I have v2021R1 ANSYS installed. Thanks

**Comment by rlagha** [comment]
@settyakshay is this possible for you to upgrade to v2021R2?

**Comment by settyakshay** [comment]
@rlagha I can but it might take sometime to download and install. I will do it in parallel. Is there any other work around to get this running for v2021R1?

**Comment by rlagha** [comment]
then you will need to install previous version of ansys.dpf.core but I'd recommend you to install 2021R2

**Comment by settyakshay** [comment]
@rlagha I installed ANSYSv2021R2 and the issue is resolved. Thanks

**Comment by rlagha** [comment]
Great thanks for the update @settyakshay. 

Ramdane
