### ISSUE TITLE
datasource set_result_path_file question

### ISSUE THREAD

**Issue by Amrit-Hub** [pyansys/pydpf-core#165]
I believe DataSources.set_result_file_path is used to add different result file path to data source. I have two result files. When I add second path using set_result_file_path, it shows the first path added as two elements.
![image](https://user-images.githubusercontent.com/94331599/152011259-cf0d4e36-29e5-48dc-93af-ef29b89ab075.png)

This shouldn't happen right? It should add the second path in the list.

**Comment by cbellot000** [comment]
Hello @Amrit-Hub, thank you for reporting this issue. There is indeed a bug server side that we'll address in the next Ansys release. In the meantime, if you'd like to look at what your data sources contains, you can use:
`print(datasource)`
