### ISSUE TITLE
Examples section and APIs section of documentation not building properly

### ISSUE THREAD

**Issue by JennaPaikowsky** [pyansys/pydpf-core#182]
I cloned the repo and created a test branch off Master. I followed the instructions to build  the docs and they built but with a bunch of errors. The API section is blank and the Example section has broken images and errors. I have attached my local build so you can see the issues too
[build.zip](https://github.com/pyansys/pydpf-core/files/8180863/build.zip)
.

**Comment by cbellot000** [comment]
@JennaPaikowsky, do you run the script in ci/build_doc.bat? that might help

**Comment by PProfizi** [comment]
Hi @JennaPaikowsky, I guess this is ok now, closing as stale. Please reopen if still relevant.
