### ISSUE TITLE
[Question / Enhancement] How to do screenshot of plots?

### ISSUE THREAD

**Issue by jfthuong** [pyansys/pydpf-core#193]
2 functions mention `off_screen` argument to be easier for doing a screenshot:
* https://dpfdocs.pyansys.com/api/ansys.dpf.core.plotter.html?highlight=screenshot#ansys.dpf.core.plotter.Plotter.plot_chart
* https://dpfdocs.pyansys.com/api/ansys.dpf.core.meshed_region.html?highlight=screenshot#ansys.dpf.core.meshed_region.MeshedRegion.plot

But the question remains: how to perform a screenshot (i.e. save to a file) a given plot?

I tried using `off_screen=True` and it does not seem to do anything.

With `pymapdl`, you could do something like:
```python
result = pymapdl_reader.read_binary("knight data/Kight_vv.rst")
result.plot_nodal_displacement(0,  screenshot='knight.png')
```

But using the argument `screenshot` does not seem to work in `pydpf`: so how to do?

Ideally, it would be nice to have features like the function `show` of `pyvista`:
https://docs.pyvista.org/examples/02-plot/screenshot.html
... which also gives the possibility to do `plotter.image` to be able to load the picture in matplotlib.

**Comment by jfthuong** [comment]
@PProfizi   Any idea on how to do?  [Ramdane told me to ask you :) ]

**Comment by PProfizi** [comment]
This works for a bare mesh when plotting from a model object:
`model.plot(off_screen=True, screenshot='file.png'`
as this calls directly the pyvista plot function.
I'll look into what happens for plot_contour and MeshedRegion.plot

**Comment by jfthuong** [comment]
I see...

What troubled me is that this does not work in Jupyter (at least in Jupyter run in VS Code).

Maybe we need to add an argument related to `pyvista` or `ipyvtklink` ??

**Comment by PProfizi** [comment]
#194 has been merged.

**Comment by PProfizi** [comment]
@jfthuong The keywords now work, however one has to use the combination:

> model.plot(off_screen=True, notebook=False, screenshot='model_plot.png')

for it to save the image.

It should be working for all `plot` commands.

**Comment by PProfizi** [comment]
Fixing the behavior for certain plot commands when in a Jupyter notebook and using notebook=False with #259.

**Comment by PProfizi** [comment]
Yet, the answer stands:
If you want to make a screenshot from within a notebook, you should use the combination of options (notebook=False, screenshot=***) whether or not `off_screen` is active. `off_screen` will only prevent the GUI from appearing.
The notebook=False is currently required for screenshots.
This is a PyVista issue, see [here](https://github.com/pyvista/pyvista/issues/1635) and [here](https://github.com/pyvista/pyvista/issues/1877)
