### ISSUE TITLE
Not able to access data from fields_container() in linux

### ISSUE THREAD

**Issue by settyakshay** [pyansys/pydpf-core#203]
Hi,

I am trying to develop the pyANSYS script to export harmonic stresses.
I need to access the output field (stress values scoped to named selection at different frequencies). The script is working fine in local windows machine.

But the linux machine throws error while accessing the output field. The error says like below:

File "/home/amd8kor/.conda/envs/pyenv/lib/python3.9/site-packages/ansys/dpf/core/errors.py", line 114, in wrapper
    raise DPFServerException(details) from None

DPFServerException: S:25<-Data sources not defined

I am also attaching the script for your reference. Kindly help!
[standalone_pyANSYS_script_to_export_harmonic_stresses_v1_HPC.zip](https://github.com/pyansys/pydpf-core/files/8370793/standalone_pyANSYS_script_to_export_harmonic_stresses_v1_HPC.zip)

**Comment by rlagha** [comment]
Hi @settyakshay , it looks like the stress provider operator is not connected to any data source, you need to do one of the following:
1.instanciate the operator using the model instead of ```dpf : op_s = model.results.stress()```
or
2. instantiate the operator as you did and connect the data sources afterward: ```s.inputs.data_sources.connect(my_data_sources)```

**Comment by settyakshay** [comment]
Cool.. Its working now. Thanks!

**Comment by settyakshay** [comment]
Cool.. Its working now. Thanks!!
