### ISSUE TITLE
Add wheelhouse to CI/CD

### ISSUE THREAD

**Issue by akaszynski** [pyansys/pydpf-core#228]
In support of offline deployment, we need to add a wheelhouse generation and deployment step to our CI/CD. This has been implemented in PyMAPDL:

https://github.com/pyansys/pymapdl/blob/45c89eab352993c3bac237e73e3558974653af84/.github/workflows/ci.yml#L93-L107

This creates *zip artifacts and uploads them on each release step. You'll need to add in additional "smoke tests" for Python 3.7 - 3.9 on Windows and Linux to generate the necessary wheels.

Finally, add or modify a release step to deploy those artifacts automatically for the release. See:

https://github.com/pyansys/pymapdl/blob/45c89eab352993c3bac237e73e3558974653af84/.github/workflows/ci.yml#L318-L361

Specifically:
https://github.com/pyansys/pymapdl/blob/45c89eab352993c3bac237e73e3558974653af84/.github/workflows/ci.yml#L342-L349

**Comment by PProfizi** [comment]
Hey @akaszynski I just started looking into this now I am available, and it seems the wheels are already deployed to Pypi for DPF-Core (see [here](https://pypi.org/project/ansys-dpf-core/0.4.1/#files)).
Is the goal only to get this, and if so is the current method ok, or is it necessary to make our CI more in line with what is done in PyMAPDL?

**Comment by PProfizi** [comment]
@akaszynski see artifacts of example run for wheelhouse generation [here](https://github.com/pyansys/pydpf-core/actions/runs/2295667394)
as well as #230 
As mentioned by @rlagha I will need to check that all wheels in there are in the list of authorized packages, and if not register them.

Is that what is required?

**Comment by akaszynski** [comment]
> Does that completely answer the current need?

Provided the artifacts are also uploaded (automatically) on a release step, it does.

Nice work!

**Comment by PProfizi** [comment]
reopening as questions still need answering before merging:

- package requirements for plotting such as pyvista?
- only create wheelhouses for os/python combinations that have been tested and can be certified?

**Comment by PProfizi** [comment]
Active starting with #351
