### ISSUE TITLE
Create animations of results in PyDPF

### ISSUE THREAD

**Issue by pmaroneh** [pyansys/pydpf-core#231]
### Description of the feature

Users would like to be able to create animated plots of the results (like the .avi file you get in Mechanical or ANDSCL command in MAPDL to animate nodal displacement) and be able to export the animation to an external file (.avi, .mp4, .gif, ...)

### Steps for implementing the feature

Tbh, I don't know.

### Useful links and references

Either.

**Comment by natter1** [comment]
Wouldn't it be possible to do it in a similar way as in [animate_nodal_solution](https://readerdocs.pyansys.com/user_guide/loading_results.html?highlight=animate_nodal_solution#ansys.mapdl.reader.rst.Result.animate_nodal_solution)?
