### ISSUE TITLE
invalid hyperlink located in Contributing page

### ISSUE THREAD

**Issue by jgd10** [pyansys/pydpf-core#245]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

![image](https://user-images.githubusercontent.com/12530336/170239772-2ead6868-34f2-436a-9ddf-0a8dee6834c9.png)
As you can see in this screenshot, under the Questions heading there is a broken markdown hyperlink to Alex's support email. Should be a relatively straightforward fix.

### Steps To Reproduce

Visible on the published docs.

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.8

### Installed packages

N/A

**Comment by PProfizi** [comment]
PyAEDT ReadMe.rst: To reach the project support team, email `pyansys.support@ansys.com <pyansys.support@ansys.com>`_.
PyMAPDL doc: To reach the project support team, email [pyansys.support@ansys.com](mailto:pyansys.support%40ansys.com).

Hi @jgd10 
I think the direct mail to Alex's email as support should be removed and replaced with the generic support mail used everywhere else.
While doing this change I will make sure it prints out correctly. Same problem on PyDPF-Post.
