### ISSUE TITLE
Volume Field Scoping Mismatch

### ISSUE THREAD

**Issue by akaszynski** [pyansys/pydpf-core#25]
Got some strange results in the following example:
```py
>>> import ansys.dpf.core as dpf
>>> from ansys.dpf.core import examples
>>> model = dpf.Model(examples.static_rst)
>>> vol = model.results.volume()
>>> field = vol.outputs.fields_container()[0]
DPF elemental_volume_1.s Field
    Location:   Elemental
    Unit:       m^3
    Num. id(s): 12
    Shape:      12
```

There are 12 items in the elemental field despite the model only having 8 elements.  Additionally, the scoping includes element IDs that do not exist in the model:
```py
>>> field.scoping.ids
[5, 6, 1, 2, 33, 35, 7, 8, 3, 4, 34, 36]
```

```py
>>> model.metadata.meshed_region.elements.scoping.ids
[5, 6, 1, 2, 7, 8, 3, 4]
```

**Comment by akaszynski** [comment]
Seems that using `'element::volume'` works:

```
vol_op = dpf.Operator('element::volume')
vol_op.inputs.mesh(model.metadata.meshed_region)
vol_op.outputs.field()
```

**Comment by akaszynski** [comment]
By default, the "available results" data we get from ``result_info`` contains the following ``AvailableResult``:

```
volume
Operator name: "ENG_VOL"
Number of components: 1
Dimensionality: scalar
Homogeneity: volume
Units: m^3
```

Since ``'element::volume'`` works and ``'ENG_VOL'`` appears to have issues (at least with this result), we may want to deprecate one.

**Comment by cbellot000** [comment]
@akaszynski after looking into the model, I see that it has SURF154 elements that are not handled by DPF. Those elements are consequently not read into the mesh, but the ENG_VOL results are taken as they are in the rst file (with the SURF154 elements).
Concerning the `element::volume` operator, it's a completely different operator that computes (and not read) the volume.

**Comment by akaszynski** [comment]
Hi @cbellot000,
Will this be fixed in the next release?

**Comment by cbellot000** [comment]
@rlagha do we plan on handling the SURF154 elements?

**Comment by rlagha** [comment]
These elements are created by the solver to define loads, We do not read them when requesting the mesh from an rst file to avoid having huge meshes. If this is needed we can add an explicit pin to read additional element types when requesting the mesh. @cbellot000 @akaszynski
