### ISSUE TITLE
Environment variable ANSYS_PATH is not used

### ISSUE THREAD

**Issue by PProfizi** [pyansys/pydpf-core#250]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

The ANSYS_PATH environment variable, despite being described in an Error message as the way to indicate a custom ANSYS installation folder, is not used in the code (server.py/start_local_server). Despite the "ansys_path" argument in the signature of start_local_server, if None, only the AWP_ROOTXXX of the most recently supported version, as well as regular C:/Program Files/ANSYS Inc/vXXX folders are checked.

The argument should be used, if None, then use ANSYS_PATH, and if None, then look for Ansys installations at AWP_ROOT and default install folder.

### Steps To Reproduce

Having an older ANSYS install in a custom repository should reproduce the error.

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.9

### Installed packages

NA

**Comment by tartarini** [comment]
any updates?
