### ISSUE TITLE
Python 3.6 Support to CI

### ISSUE THREAD

**Issue by akaszynski** [pyansys/pydpf-core#32]
Add this to the CI for Windows/Linux

**Comment by PProfizi** [comment]
Hi @akaszynski , cleaning-up the PyDPF-Core issues. Did you mean for the CI to include testing for Python 3.6?

**Comment by PProfizi** [comment]
Hi @akaszynski. 
As far as I understand it this issue was about supporting 3.6, which we do not plan to do. Closing as wontfix.
