### ISSUE TITLE
Use v* for tags

### ISSUE THREAD

**Issue by akaszynski** [pyansys/pydpf-core#370]
There are a few good reasons for this:
- GitHub has [protected tags](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules), something that @anslpa had brought up last year and I agreed that was missing from GitHub. In order for us to use this we have to have a rule that selects based on a string match like `v*`
- It makes it much easier to checkout a versioned tag via `git checkout v` followed by a tab.
- It seems to be quite common. See this [SO question/answer](https://stackoverflow.com/questions/37781073/why-github-suggest-prefix-your-version-names-with-the-letter-v).

**Comment by akaszynski** [comment]
@jorgepiloto, let's add some guidance/recommendation regarding this in https://dev.docs.pyansys.com/. I used to not follow this practice and I might have lead a few projects astray.

**Comment by jorgepiloto** [comment]
Thanks for pinging, @akaszynski. Addressing this!

**Comment by PProfizi** [comment]
@jorgepiloto I've added the protection rule for tags v* as per the recommendation.

**Comment by PProfizi** [comment]
Closing as this has now been merged with  #434 and should have been closed automatically.
