### ISSUE TITLE
Support for Python 3.10

### ISSUE THREAD

**Issue by RobPasMue** [pyansys/pydpf-core#383]
### Description of the feature

Apparently, ``pydpf-core`` is not supported on Python 3.10. On the https://github.com/pyansys/pyansys-landing repository (the PyAnsys metapackage project), we are working on supporting all Python versions from 3.7 onwards. Is there a specific reason for this not to be possible with ``pydpf-core``?

### Steps for implementing the feature

Try supporting Python 3.10. Investigate problematic requirements and needs.

**Comment by PProfizi** [comment]
Hi @RobPasMue. I think it might only be a mistake in the setup.py. We have one last major merge to do and I will investigate whether 3.10 is really supported, and if so update the package metadata.

**Comment by RobPasMue** [comment]
Oh that'd be great @PProfizi! A good way of checking the support for different Python versions is setting up a "Smoke tests" stage in your CI in which you try to build your project in different OS and Python versions, and then just check a simple import test (to see if the version is read correctly, for example).

If you want more details I can redirect you to some examples: 
* PyDisco: https://github.com/pyansys/pydisco/blob/3b909c98d09682db8caf002385b695089d974d02/.github/workflows/ci_cd.yml#L57-L134
* PyMAPDL: https://github.com/pyansys/pymapdl/blob/4e7a8dad680ba11fd4fd8915e99b07f6210b8bc1/.github/workflows/ci.yml#L50-L111
* PyFluent: https://github.com/pyansys/pyfluent/blob/f130ca0a5ad2acd0a34d795795d84217876c81c9/.github/workflows/ci.yml#L67-L105

Please ping me if you need any kind of support with this.

**Comment by PProfizi** [comment]
@RobPasMue Yes I saw the different packages doing that, however we were thinking of doing a bit more than just smoke tests, like running all our examples, which shouldn't take that long.
I'll take the opportunity to generate all the corresponding wheelhouses.

**Comment by RobPasMue** [comment]
That sounds like a good idea as well! Go for it. Thanks @PProfizi, I'll keep an eye on whatever you end up implementing if you want :)

**Comment by RobPasMue** [comment]
Hi @PProfizi did you manage to look into both the https://github.com/pyansys/pydpf-core anf https://github.com/pyansys/pydpf-post to see what was the issue with Python 3.10?

**Comment by RobPasMue** [comment]
From what I see in the setup files, it looks like the most restrictive one is https://github.com/pyansys/pydpf-post... They are explicitly excluding Python 3.10

```
...
    python_requires=">=3.7.*,!=3.10.*",
```

Whereas https://github.com/pyansys/pydpf-core does allow for Python 3.10
```
...
    python_requires=">=3.7.*,
```

**Comment by PProfizi** [comment]
Hi @RobPasMue , yes I have had a small look while working on the release workflow.

Indeed it is PyDPF-Post which restricts 3.10. That is because right now PyDPF-Post restricts vtk<=9.1.0, which does not work with 3.10. However, when I remove the constrain on vtk, then all windows builds fail.
Right now I had to make a choice between releasing for Windows and Linux 3.7 to 3.9, or releasing only for Linux.
Will be working on removing the limitation for vtk<9.1.0 next. FYI we get a windows memory error.
So, PyDPF-Core does not explicitely restrict 3.10, because for now there is no smoke test and no specific bug has been reported. But I could not, for Post, release with support for 3.10 when the pipeline does test it and it fails.

**Comment by RobPasMue** [comment]
Agreed! Yes, that's why I could infer from the ``setup.py`` files. We should try and solve that limitation on ``PyDPF-Post``so that it does not affect the rest of the PyAnsys packages. Thanks for looking into it. Please keep me posted. We will move to issues https://github.com/pyansys/pydpf-post/issues/107 and https://github.com/pyansys/pydpf-post/issues/113 to discuss both the ``vtk`` restriction and allowing Python 3.10 on PyDPF-Post. Thanks @PProfizi!

**Comment by PProfizi** [comment]
See #403 
A vtk<9.1.0 limitation was hidden in the requirements_test.txt, meaning that all testing up until now has been done with vtk 9.0.3.
When testing without this requirement, one can see the same errors as for PyDPF-Post, meaning a vtk memory error for all Windows runners.
