### ISSUE TITLE
mesh.plot error on Ansys Lab

### ISSUE THREAD

**Issue by PProfizi** [pyansys/pydpf-core#399]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpfdocs.pyansys.com/getting_started/index.html#compatibility) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

mesh.plot(field) on Ansys Lab throws a 

pv_pythreejs.py
--> 118 return pv.wrap(table.MapScalars(scalars, 0, 0))[:, :3]/255
"TypeError: ambiguous call, multiple overloaded methods match the arguments"

### Steps To Reproduce

On Ansys Lab, create a field and use
mesh.plot(field)

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

Unknown

**Comment by PProfizi** [comment]
Hi @jleonatti, creating an Issue here. 
Would it be possible for you to list the packages installed, the Python version... etc?
I have yet to familiarize with the configuration of Ansys Lab.
I will also update the bug issue template to enable Ansys Lab-related choices in the form.

**Comment by jleonatti** [comment]
Thanks for this @PProfizi. The DPF packages installed on Ansys Lab from executing `pip list` show:

ansys-dpf-core                         0.5.1
ansys-dpf-gate                         0.1.0
ansys-dpf-post                         0.2.2
ansys.grpc.dpf                         0.5.0

**Comment by PProfizi** [comment]
Thank you @jleonatti.

I remember hearing you would prefer installing via pip?
One first thing we could try is installing the latest versions of each package. Is that possible?
The ansys-dpf-core 0.5.1 version dates back a little.

ansys-dpf-core 0.5.2
ansys-dpf-gate 0.1.2
ansys-dpf-post 0.2.3
ansys.grpc.dpf 0.5.2

**Comment by jleonatti** [comment]
@PProfizi I can try out upgrading the packages. I will let you know when I have tested it.

**Comment by jleonatti** [comment]
I upgraded all the dpf packages with the following:

```
pip install --upgrade ansys-dpf-core
pip install --upgrade ansys-dpf-gate
pip install --upgrade ansys-dpf-post
pip install --upgrade ansys-grpc-dpf
```

Now the packages have been updated (and one added):

```
ansys-dpf-core                         0.5.2
ansys-dpf-gate                         0.1.2
ansys-dpf-gatebin                      0.1.2
ansys-dpf-post                         0.2.3
ansys-grpc-dpf                         0.5.2
```

I am seeing a different issue now with the same Average Elemental Stress template:

![image](https://user-images.githubusercontent.com/84793532/184233265-078989de-27ba-403a-9c90-88eaf1801b48.png)

Any ideas here?

**Comment by PProfizi** [comment]
Hi @jleonatti, I see your path is /mnt/ansys_inc/v212, are you using ANSYS R212?

**Comment by cbellot000** [comment]
Hi @jleonatti, we forgot to send you an update when we released our last version of python.
We changed our default configuration to in process (meaning that be default, when possible, we don't use gRPC to communicate between python and DPF), so when we try to locate a server or to load DPF in process, we first look for a local install of DPF, and it looks like you have either an AWP_ROOT variable on your client image or/and an install /mnt/ansys_inc/.

To fix this issue, you can either remove the 2 mentioned things above or set the environment variable DPF_SERVER_TYPE=GRPC on your client image

**Comment by jleonatti** [comment]
Hi @cbellot000, okay thanks for letting me know. I set the environment variable you specified. Thanks!

**Comment by jleonatti** [comment]
That fixed the issue. I will work to upgrade the DPF packages and add this environment variable to our Ansys Lab image. Thanks!

**Comment by jleonatti** [comment]
With a new image that contains upgraded dpf packages and the DPF_SERVER_TYPE=GRPC running on the cluster, I am see a new error in the notebook:

```
File /opt/conda/lib/python3.9/site-packages/ansys/dpf/gate/generated/scoping_capi.py:89, in ScopingCAPI.scoping_get_ids_for_dpf_vector(scoping, out, data, size)
     87 res = capi.dll.Scoping_GetIds_For_DpfVector(scoping._internal_obj, out._internal_obj, utils.to_int32_ptr_ptr(data), utils.to_int32_ptr(size), ctypes.byref(utils.to_int32(errorSize)), ctypes.byref(sError))
     88 if errorSize.value != 0:
---> 89 	raise errors.DPFServerException(sError.value)
     90 return res

DPFServerException: failed to GetIds for scoping
```

I am attaching the output of the notebook as html in the zip. 
[02-volume_averaged_stress_1.zip](https://github.com/pyansys/pydpf-core/files/9328938/02-volume_averaged_stress_1.zip)

You can try it out for yourselves on https://jupyter.dev.ansysapis.com/ and select the APOD dev image (dev2) image and then run the Average Elemental Stress example.

![image](https://user-images.githubusercontent.com/84793532/184415796-d67e0cad-5f18-4705-b9a5-1660f6aee38d.png)
