### ISSUE TITLE
Add Material API implementation

### ISSUE THREAD

**Issue by germa89** [pyansys/pydpf-core#437]
### Description of the feature

We should aim to have a comprehensive materials API in DPF.

At the moment there are many operators in place, but I believe they lack the "connection" between them in order to expose these feature properly.

As first step, let's talk about how the API should look like. Then we can decide how to couple the operators in order to obtain the desired API.

### Steps for implementing the feature

Personally, I would propose the following pseudo-code for the API.

## Proposed implementation

```py
>>> from ansys.dpf import core as dpf
>>> import numpy as np

>>> model = dpf.Model('file.rst')

>>> mat1 = model.materials.get_material(1)
>>> mat1.name = "Structural Steel"
>>> mat1.id = "1"
>>> mat1.uud = "asdf-asdf-asdf-asdf" #whatever thing is named.
>>> mat1.units = "MKS"

>>> mat1.add_density(7900)
>>> mat1.add_isotropic_elasticity(ex=1E9, nu=0.3)

>>> mat1
Material 1: Structural Steel
uud: asdf-asdf-asdf-asdf
Properties
----------
Density: 7900 kg/m3
Isotropic Elasticity:
	EX = 1E9 N/m2
	NU = 0.3
>>> mat1.ex # we should be able to use MAPDL labels (EX, NUXY, KXX, etc) to get the info.
1E9
>>> mat1['EX']
1E9

>>> mat1.dens = 8000
>>> mat1.dens
8000

>>> from ansys.dpf import units, custom_unit
>>> my_custom_units = custom_unit(lenght=units.lenght.mm,
temperature=units.temperature.C) # rest default to MKS.
>>> from ansys.dpf.core import Physics
>>> mat1.add_isotropic_resistivity(
	values = np.array([1, 2, 3, 4])*1E-9,
	reference = Physics.temperature,
	reference_values = [10, 20, 30, 40],
	units = my_custom_units
	)
>>> mat1.kxx
Isotropic Resistivity
Temperature dependent
Values Temperature
1E-9	10
2E-9	20
3E-9	30
4E-9	40
>>> mat1.kxx.units
Lenght: mm
Temperature: C
Mass: Kilograms
Time: Seconds
...
>>> mat1.kxx.units(lenght=units.lenght.m)
>>> mat1.kxx.units
Lenght: m
Temperature: C
Mass: Kilograms
Time: Seconds
```

I believe this API is pythonic enough but also rigorous enough to allow a clear material definition.

Personally, it is the kind of thing I would like to see in PyMAPDL. 

Please, feel free to propose modification.

I'm happy to discuss this.

**Comment by germa89** [comment]
Pinging @PProfizi for updates and improvements.

Pinging @cbellot000 @ayush-kumar-423 @janvonrickenbach @rlagha 

Pinging @akaszynski @koubaa because they probably are interested (maybe)

**Comment by PProfizi** [comment]
@germa89 In your pseudo-code you propose a lot of setters, yet I am not sure if this is something we should make available (at least at first) as to me that would entail actually changing the values stored at the server level, maybe even in the material files? What would be the expected outcome of those setters? This seems like pre-treatment to me and I do not see a direct usage for this, but I may definitely be biased.
