### ISSUE TITLE
Minor Documentation typo

### ISSUE THREAD

**Issue by rajesh1359** [pyansys/pydpf-core#477]
There is a typo in the documentation at the Custom Operator page (https://dpf.docs.pyansys.com/user_guide/custom_operators.html#use-the-custom-operators). The underscore should be after 'py' i.e 'py_'.

![image](https://user-images.githubusercontent.com/60212378/189673124-8f344265-d37b-4d21-8bc6-06c2537f3df4.png)

**Comment by PProfizi** [comment]
@rajesh1359 good catch, thank you!
