### ISSUE TITLE
Outdated documentation refering to Ansys requirements

### ISSUE THREAD

**Issue by germa89** [pyansys/pydpf-core#478]
### Description of the bug

The documentation seems outdated regarding the need of having ANSYS installed. I believe it is not needed to have ANSYS installed anymore. 

### Links

* https://github.com/pyansys/pydpf-core#installation
* https://dpf.docs.pyansys.com/getting_started/compatibility.html#client-server

**Comment by PProfizi** [comment]
Hi @germa89, it is indeed required for now to have Ansys installed. We will change the documentation once a standalone version of DPF is released to the public, yet in the meantime, if that's okay with you, I'll mark this issue as stale.
