### ISSUE TITLE
Add averaging from ``ElementalNodal`` to ``Elemental``

### ISSUE THREAD

**Issue by germa89** [pyansys/pydpf-core#492]
### Description of the feature

It seems that averaging from ``ElementNodal`` to ``Elemental`` is not implemented yet. Any estimated time to implement this??

```text
DPFServerException: S:34<-averaging from ElementalNodal to elemental is not implemented
```

### Steps for implementing the feature

RST file: 
[file.zip](https://github.com/pyansys/pydpf-core/files/9615941/file.zip)

```py
from ansys.dpf import core as dpf

model = dpf.Model("file.rst") # From vm33
mesh = model.metadata.meshed_region

field_op = model.results.stress()

my_scoping = dpf.Scoping()
my_scoping.location = "elemental"

my_scoping.ids = mesh.elements.scoping.ids # To select all

field_op.inputs.mesh_scoping.connect(my_scoping)

container = field_op.outputs.fields_container()[0] # DPFServerException: S:34<-averaging from ElementalNodal to elemental is not implemented

```

**Comment by germa89** [comment]
Sugerencia: usar ``elementalnodal`` to ``nodal`` to ``elemental``.

**Comment by cbellot000** [comment]
@germa89 "elemental" is not the supported string, "Elemental" is. You can get the supported locations in `dpf.locations.`.
FYI @PProfizi @rafacanton

**Comment by germa89** [comment]
😮 

https://media.giphy.com/media/90F8aUepslB84/giphy.gif

**Comment by germa89** [comment]
Yes. But I think these kind of string keyword argument should not be case sensitive.
