### ISSUE TITLE
Operator does not sort output field according the mesh scope

### ISSUE THREAD

**Issue by germa89** [pyansys/pydpf-core#535]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/getting_started/index.html#compatibility) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

It seems that the result is not ordered accorded to the ``Scoping`` object.

### Steps To Reproduce

Open the attached RST file.

[file.zip](https://github.com/pyansys/pydpf-core/files/9726426/file.zip)

This file is generated from VM223 (electro-thermal microactuator analysis).

If you open this RST on MAPDL GUI and run ``PRNSOL,U,X``, you obtain:
```text
PRINT S    ELEMENT SOLUTION PER ELEMENT
   *****MAPDL VERIFICATION RUN ONLY*****
     DO NOT USE RESULTS FOR PRODUCTION


 Reason COMPARE differences are acceptable:
 Convergence Difference

 ***** POST1 ELEMENT NODAL STRESS LISTING *****

  LOAD STEP=     1  SUBSTEP=     1
   TIME=    1.0000      LOAD CASE=   0

  THE FOLLOWING X,Y,Z VALUES ARE IN GLOBAL COORDINATES


  ELEMENT=       1        SOLID227
    NODE     SX           SY           SZ           SXY          SYZ          SXZ
     750 -0.39919E+007 0.27411E+008 0.65745E+007-0.44497E+007 0.79310E+006  93510.
    1585  0.72200E+007 0.44622E+008 0.14827E+008-0.12982E+008-0.59760E+006-0.31261E+006
     136 -0.44059E+008-0.52287E+008-0.19917E+008 0.32285E+008-0.91023E+006-0.31334E+007
    1877 -0.87202E+007-0.35306E+008-0.14740E+007 0.13838E+008-0.10353E+007 0.24730E+007

  ELEMENT=       2        SOLID227
    NODE     SX           SY           SZ           SXY          SYZ          SXZ
    1084  0.10405E+008 0.20293E+006 0.11267E+006-0.13490E+006 -34269.       91864.
    2115 -0.93631E+007-0.74796E+006 -38049.     -0.45902E+006  17073.       76040.
     905 -0.33174E+008 0.39291E+006-0.18813E+006-0.23480E+006 -29526.     -0.17083E+006
     249  0.11067E+008 0.16107E+006 0.16020E+006 -81686.      -29410.      -54730.

  ELEMENT=       3        SOLID227
    NODE     SX           SY           SZ           SXY          SYZ          SXZ
      14 -0.15268E+007 0.20698E+007 0.63538E+006-0.66089E+006-0.11125E+007-0.19376E+006
```

Then if you try to obtain the same sort of results, you do:

```py
import numpy as np
import os
from ansys.dpf import core as dpf

RST_file = os.path.join("file.rst")
model = dpf.Model(RST_file)
mesh = model.metadata.meshed_region

post_ids = np.array([ 750, 1585,  136, 1877, 1084, 2115,  905,  249,   14])  # From ``PRNSOL``

op = model.results.stress()

my_scoping = dpf.Scoping()
my_scoping.location = "Nodal"
my_scoping.ids = post_ids.astype(int).tolist()

op.inputs.mesh_scoping.connect(my_scoping)

res = op.outputs.fields_container()[0].data
```
Printing ``res`` results in:
```py
>> res
DPFArray([[-6.37108250e+06,  3.69760286e+02,  3.53100510e+01,
            7.98998357e+02,  9.27671509e+01, -3.52340652e+02],
          [-2.22203964e+06, -1.34483819e+02,  3.05809882e+02,
            5.16565112e+04,  4.64120246e+01,  5.46715873e+00],
          [-6.36420381e+06, -2.38479757e+01,  2.71445160e+02,
            6.12205609e+03, -1.30899710e+02, -2.44380106e+02],
          ...,
          [-2.05811825e+07, -1.90712949e+04, -2.03495710e+04,
           -2.56856965e+05, -5.47159523e+03, -8.05424408e+03],
          [-2.02615190e+07,  1.63991809e+05,  3.88981250e+04,
           -2.94374673e+05, -8.21834277e+03,  2.76083863e+04],
          [-2.00190340e+06,  1.71016377e+04,  1.33130830e+04,
           -4.07396656e+05,  2.02739437e+04, -1.86581089e+04]])
```
As you can see, the values do not match.

However if do the scoping on a single element:

```py
op = model.results.stress()

my_scoping = dpf.Scoping()
my_scoping.location = "Elemental"
my_scoping.ids = [1]

op.inputs.mesh_scoping.connect(my_scoping)

res = op.outputs.fields_container()[0].data
```
Then the results are as expected:
```py
>>> print(res)
DPFArray([[ -3991905.       ,  27410738.       ,   6574541.       ,
            -4449703.5      ,    793095.625    ,     93509.8828125],
          [  7219965.       ,  44621772.       ,  14827338.       ,
           -12982476.       ,   -597602.375    ,   -312610.625    ],
          [-44058608.       , -52287380.       , -19917276.       ,
            32284676.       ,   -910232.6875   ,  -3133419.       ],
          [ -8720216.       , -35305808.       ,  -1474001.875    ,
            13838160.       ,  -1035323.375    ,   2472966.5      ]])
```

It seems the problem arises from selecting multiple elements, because:

```py
op = model.results.stress()

my_scoping = dpf.Scoping()
my_scoping.location = "Elemental"
my_scoping.ids = [1, 2] 

op.inputs.mesh_scoping.connect(my_scoping)

res = op.outputs.fields_container()[0].data
```
returns:
```py
DPFArray([[ 1.04053630e+07,  2.02928875e+05,  1.12674117e+05,
           -1.34898016e+05, -3.42685156e+04,  9.18637812e+04],
          [-9.36311700e+06, -7.47957812e+05, -3.80491289e+04,
           -4.59018406e+05,  1.70726406e+04,  7.60397734e+04],
          [-3.31743480e+07,  3.92909375e+05, -1.88131812e+05,
           -2.34804812e+05, -2.95260996e+04, -1.70829344e+05],
          [ 1.10672610e+07,  1.61067281e+05,  1.60197547e+05,
           -8.16856562e+04, -2.94103574e+04, -5.47297734e+04],
          [-3.99190500e+06,  2.74107380e+07,  6.57454100e+06,
           -4.44970350e+06,  7.93095625e+05,  9.35098828e+04],
          [ 7.21996500e+06,  4.46217720e+07,  1.48273380e+07,
           -1.29824760e+07, -5.97602375e+05, -3.12610625e+05],
          [-4.40586080e+07, -5.22873800e+07, -1.99172760e+07,
            3.22846760e+07, -9.10232688e+05, -3.13341900e+06],
          [-8.72021600e+06, -3.53058080e+07, -1.47400188e+06,
            1.38381600e+07, -1.03532338e+06,  2.47296650e+06]])
```
Which is basically the expected results, but first the element 2, and later the element 1.

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.9

### Installed packages

<details><summary> Show me! </summary>

aiohttp==3.8.1
aiosignal==1.2.0
alabaster==0.7.12
ansys-api-mapdl==0.5.1
ansys-api-platform-instancemanagement==1.0.0b3
-e git+https://github.com/pyansys/pydpf-core.git@3977c3952a6d67ceb67390fe7ea7a862b8389c6c#egg=ansys_dpf_core
ansys-dpf-gate==0.2.1
ansys-dpf-gatebin==0.2.1
-e git+https://github.com/pyansys/pydpf-post.git@f9a6412f906a0e70c1a3a7fe19b88248124933d7#egg=ansys_dpf_post
ansys-grpc-dpf==0.4.0
-e git+https://github.com/pyansys/pymapdl.git@a05cb51a9194483691c8c919f32db8cf41ec5d48#egg=ansys_mapdl_core
-e git+https://github.com/pyansys/pymapdl-reader@e52968656a402f5aae4753e70c3709452cc714f6#egg=ansys_mapdl_reader
ansys-platform-instancemanagement==1.0.2
ansys-sphinx-theme==0.4.2
anyio==3.5.0
appdirs==1.4.4
argcomplete==2.0.0
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.5
async-timeout==4.0.2
atomicwrites==1.4.0
attrs==21.4.0
autobahn==22.2.2
Automat==20.2.0
autopep8==1.6.0
Babel==2.9.1
backcall==0.2.0
beautifulsoup4==4.11.1
black==22.1.0
bleach==4.1.0
build==0.8.0
cachetools==5.0.0
certifi==2021.10.8
cffi==1.15.0
cfgv==3.3.1
charset-normalizer==2.0.12
click==8.0.4
colorama==0.4.4
commonmark==0.9.1
constantly==15.1.0
coverage==6.3.2
cryptography==36.0.1
cycler==0.11.0
debugpy==1.5.1
decorator==5.1.1
defusedxml==0.7.1
distlib==0.3.4
dnspython==2.2.0
docopt==0.6.2
docutils==0.17.1
entrypoints==0.3
esbonio==0.11.0
executing==0.8.2
fett==0.3.2
filelock==3.6.0
flake8 @ file:///opt/conda/conda-bld/flake8_1648129545443/work
fonttools==4.29.1
frozenlist==1.3.0
geomdl==5.3.1
google==3.0.0
google-api-core==2.5.0
google-api-python-client==2.37.0
google-auth==2.6.0
google-auth-httplib2==0.1.0
googleapis-common-protos==1.54.0
grpcio==1.43.0
httplib2==0.20.4
hyperlink==21.0.0
identify==2.4.11
idna==3.3
imageio==2.19.3
imageio-ffmpeg==0.4.7
imagesize==1.3.0
importlib-metadata @ file:///C:/ci/importlib-metadata_1648562621412/work
incremental==21.3.0
iniconfig==1.1.1
ipycanvas==0.12.0
ipydatawidgets==4.2.0
ipyevents==2.0.1
ipykernel==6.9.1
ipython==8.0.1
ipython-genutils==0.2.0
ipyvtklink==0.2.2
ipywidgets==7.6.5
jedi==0.18.1
Jinja2==3.1.2
json5==0.9.6
jsonschema==4.4.0
jupyter==1.0.0
jupyter-client==7.1.1
jupyter-console==6.4.0
jupyter-core==4.9.1
jupyter-server==1.13.5
jupyter-sphinx==0.4.0
jupyterlab==3.3.3
jupyterlab-pygments==0.1.2
jupyterlab-server==2.10.3
jupyterlab-widgets==1.0.2
keyring==23.6.0
kiwisolver==1.3.2
livereload==2.6.3
mapdl @ file:///C:/Program%20Files/ANSYS%20Inc/v212/ANSYS/syslib/ansGRPC/User/mapdl-pyupf.tar.gz
matplotlib==3.5.2
matplotlib-inline==0.1.3
mccabe @ file:///opt/conda/conda-bld/mccabe_1644221741721/work
mpmath==1.2.1
multidict==6.0.2
mypy-extensions==0.4.3
nbclassic==0.3.5
nbclient==0.5.10
nbconvert==6.5.0
nbformat==5.2.0
nbsphinx==0.8.8
nest-asyncio==1.5.4
networkx==2.6.3
nodeenv==1.6.0
nose==1.3.7
notebook==6.4.7
numpy==1.22.2
numpydoc==1.4.0
packaging==21.3
pandas==1.4.3
pandocfilters==1.5.0
parso==0.8.3
pathspec==0.9.0
pep517==0.12.0
pickleshare==0.7.5
Pillow==9.0.1
pipx==1.0.0
pkginfo==1.8.3
platformdirs==2.5.1
plotly==5.9.0
pluggy==1.0.0
pre-commit==2.17.0
progressbar2==4.0.0
prometheus-client==0.12.0
prompt-toolkit==3.0.28
protobuf==3.19.4
protoc-gen-swagger==0.1.0
psutil==5.9.1
pure-eval==0.2.2
py==1.11.0
pyansys-sphinx-theme==0.2.3
pyansys-tools-report==0.2.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle @ file:///tmp/build/80754af9/pycodestyle_1636635402688/work
pycparser==2.21
pydantic==1.8.2
pydata-sphinx-theme==0.9.0
pyflakes @ file:///tmp/build/80754af9/pyflakes_1636644436481/work
pygls==0.11.3
Pygments==2.11.2
pyiges==0.2.1
pymongo==3.12.3
pypandoc==1.8.1
pyparsing==3.0.7
pyrsistent==0.18.1
pyspellchecker==0.6.3
pytest==7.0.1
pytest-cov==3.0.0
pytest-sphinx==0.4.0
python-dateutil==2.8.2
python-jsonrpc-server==0.3.4
python-utils==3.3.3
pythreejs==2.3.0
pytz==2021.3
pyvista @ https://github.com/pyvista/pyvista/archive/main.zip
pywin32==303
pywin32-ctypes==0.2.0
pywinpty==1.1.6
PyYAML==5.4.1
pyzmq==22.3.0
qtconsole==5.2.2
QtPy==2.0.0
readme-renderer==35.0
requests==2.27.1
requests-toolbelt==0.9.1
rfc3986==2.0.0
rich==12.4.4
rsa==4.8
rstcheck==3.3.1
scipy==1.8.0
scooby==0.5.12
Send2Trash==1.8.0
six==1.16.0
sniffio==1.2.0
snooty-lextudio==1.12.0
snowballstemmer==2.2.0
soupsieve==2.3.2.post1
Sphinx==5.0.2
sphinx-autobuild==2021.3.14
sphinx-autodoc-typehints==1.18.3
sphinx-copybutton==0.5.0
sphinx-gallery==0.10.1
sphinx-notfound-page==0.8
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
sphinxcontrib-websupport==1.2.4
sphinxemoji==0.2.0
stack-data==0.2.0
sympy==1.9
tenacity==8.0.1
terminado==0.12.1
testpath==0.5.0
tinycss2==1.1.1
toml==0.10.2
tomli==2.0.1
tornado==6.1
tox==3.25.0
tqdm==4.62.3
traitlets==5.1.1
traittypes==0.2.1
twine==4.0.1
Twisted==22.1.0
twisted-iocpsupport==1.0.2
txaio==22.2.1
typeguard==2.13.3
typing_extensions==4.1.1
uritemplate==4.1.1
urllib3==1.26.8
userpath==1.8.0
virtualenv==20.13.2
vtk==9.0.3
watchdog==1.0.2
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.3.1
widgetsnbextension==3.5.2
wincertstore==0.2
wslink==1.4.1
xlrd==2.0.1
yarl==1.7.2
zipp @ file:///opt/conda/conda-bld/zipp_1641824620731/work
zope.interface==5.4.0
</details>

**Comment by germa89** [comment]
Hi @pmaroneh 

Thank you for your answer! Indeed using ``Rescope`` operator together with ``ElementalNodal`` seems to work:

```py

post_ids = [1,2,3]

op = model.results.stress()

my_scoping = dpf.Scoping()
# my_scoping.location = "ElementalNodal" # Raises if uncommented `` DPFServerException: S:182<-averaging from ElementalNodal to ElementalNodal is not implemented``
my_scoping.ids = post_ids

op.inputs.mesh_scoping.connect(my_scoping)

fc = op.outputs.fields_container()

rescope = dpf.operators.scoping.rescope()
rescope.inputs.mesh_scoping(post_ids)
rescope.inputs.fields(fc)
rescope_field = rescope.outputs.fields_as_fields_container

res = rescope_field()[0].data
```
results in:
```py
>>> print(rescope_field.get_data()[0].scoping.ids[:10])
[1 2 3]
>>> print(res)
[[-3.99190500e+06  2.74107380e+07  6.57454100e+06 -4.44970350e+06
   7.93095625e+05  9.35098828e+04]
 [ 7.21996500e+06  4.46217720e+07  1.48273380e+07 -1.29824760e+07
  -5.97602375e+05 -3.12610625e+05]
 [-4.40586080e+07 -5.22873800e+07 -1.99172760e+07  3.22846760e+07
  -9.10232688e+05 -3.13341900e+06]
 [-8.72021600e+06 -3.53058080e+07 -1.47400188e+06  1.38381600e+07
  -1.03532338e+06  2.47296650e+06]
 [ 1.04053630e+07  2.02928875e+05  1.12674117e+05 -1.34898016e+05
  -3.42685156e+04  9.18637812e+04]
 [-9.36311700e+06 -7.47957812e+05 -3.80491289e+04 -4.59018406e+05
   1.70726406e+04  7.60397734e+04]
 [-3.31743480e+07  3.92909375e+05 -1.88131812e+05 -2.34804812e+05
  -2.95260996e+04 -1.70829344e+05]
 [ 1.10672610e+07  1.61067281e+05  1.60197547e+05 -8.16856562e+04
  -2.94103574e+04 -5.47297734e+04]
 [-1.52678600e+06  2.06977912e+06  6.35382312e+05 -6.60887750e+05
  -1.11250638e+06 -1.93757266e+05]
 [-1.27791275e+06 -5.71629800e+06 -9.54716562e+05  1.10044400e+06
   8.76255920e+02 -5.61088555e+04]
 [-1.38398350e+06  1.38538550e+06  1.18645125e+06 -1.12267712e+06
   1.89969203e+05  5.34367875e+05]
 [-1.33788525e+06 -5.42868350e+06 -5.13370094e+05  1.10572070e+07
   7.23467750e+05 -9.27796875e+05]]
```

I guess this is an erratic behavior (the ``Rescope`` operator should not be needed, and if needed, it should be always needed) which should be fixed. But I'm closing the issue, leaving it up to the project managers to re-open it or not.

Thank you!

**Comment by pmaroneh** [comment]
@germa89 I agree with you that having to use the rescope operator is not ideal, there are probably some reasons behind it but we've had several support cases about the issue that you raised and we had to explain that rescope is needed. Maybe @rlagha this is something worth considering?
