### ISSUE TITLE
Title bars need to show library names

### ISSUE THREAD

**Issue by PipKat** [pyansys/pydpf-core#54]
In the rendered doc, the title bar currently shows py[Ansys] rather the names we are giving the DPF packages. Maybe they should eventually be PyDPF-Core and PyDPF-Post? If so, the doc will likely need to be updated to match. For now, perhaps they should just be DPF-Core and DPF Post.

**Comment by akaszynski** [comment]
Good point.  We can do this by configuring the theme of `pyvista`.  Before, this used rcParams, there's now a new `theme` class.  See [Control Global and Local Plotting Themes - PyVista](https://docs.pyvista.org/examples/02-plot/themes.html).

**Comment by PProfizi** [comment]
Hi @rlagha, is that still on the to-do list? The PyMAPDL doc does use the PyAnsys logo and not a specific PyMAPDL logo. Same for PyAEDT. 
I think the politics on this went towards not using specific logos, so I will be closing this issue until further notice.
