### ISSUE TITLE
Follow semantic versioning (version X.Y.Z)

### ISSUE THREAD

**Issue by GuillemBarroso** [pyansys/pydpf-core#629]
The syntax for this version does not follow semantic versioning, see [dev guide](https://dev.docs.pyansys.com/how-to/releasing.html#semantic-versioning). We should open an issue to address this in a separate pull-request, @GuillemBarroso. I know it was originally defined like this in the `setup.py`.

_Originally posted by @jorgepiloto in https://github.com/pyansys/pydpf-core/pull/627#discussion_r1026373666_

**Comment by PProfizi** [comment]
Hi @GuillemBarroso, hi @jorgepiloto, I am not sure I understand the problem with having our master as X.Y.Z.devA.
This follows normalized semantic versioning as stated [here](https://peps.python.org/pep-0440/#development-release-separators).

**Comment by GuillemBarroso** [comment]
Hi @PProfizi, 

@jorgepiloto, correct me if I am wrong, but what I understood form the developers guide is that the agreed convention is:

- main branch: The version will always be X.Y.dev0.
- release branches: The versions here will be X.Y.Z

meaning that the minor patch number (Z) for ``main`` branch is always dev0.

**Comment by PProfizi** [comment]
For PyDPF packages, we are currently working with a "0.X.Y" format, so our third number should not be understood as "patch" but really as minor. Hence, the "0.X.Y.devA".
The reason behind keeping the first number at 0 is historical, it might change in the future.
This might not be exactly like the pyansys guidelines yet this is semantically correct.

**Comment by GuillemBarroso** [comment]
Thank you for the clarification @PProfizi.

@jorgepiloto, do you think we are going to run into some issues when integrating the pyansys/actions in PyDPF-Core?

**Comment by jorgepiloto** [comment]
I was too fast opening this issue, sorry for this. @PProfizi is right. This version follows semantic versioning, so this issue can be closed.

However, I would encourage to follow the "X.Y.dev0" for main, as this is what is being done by other libraries like PyMAPDL or PyAEDT.

**Comment by GuillemBarroso** [comment]
Thanks @jorgepiloto. Closing this issue.
