### ISSUE TITLE
Wrong contour plots when plotting subsets after full scope

### ISSUE THREAD

**Issue by janvonrickenbach** [pyansys/pydpf-core#632]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

If plotting a contour plot for a subset of the mesh, the order of the plot matters and the second plot show the wrong results. See the attached script.

These are the results if the full scope is plotted first

![image](https://user-images.githubusercontent.com/7096387/203053640-d61c9998-e677-4f03-83fe-5b738b630bfd.png)
![image](https://user-images.githubusercontent.com/7096387/203053733-8de92274-06a3-4b7a-90a3-01016a46d2ec.png)

These are the results if the subscope is plotted first (swappig the last two lines in the script).

![image](https://user-images.githubusercontent.com/7096387/203054272-4de6d218-5459-49ea-a727-6c16b3730472.png)
![image](https://user-images.githubusercontent.com/7096387/203054365-72adfa26-2197-4824-be97-8d882a3d7f60.png)

In both cases the first image shown shows the expected result

### Steps To Reproduce

* Extract the attached archive and run the python script (use the attached rst file on line 6 of the script)
[bug.zip](https://github.com/pyansys/pydpf-core/files/10056462/bug.zip)

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

aiohttp==3.8.3
aiosignal==1.2.0
alabaster==0.7.12
-e git+https://github.com/pyansys/pydpf-composites.git@44dc4bab5b3ec478084555900f0d2b1f61bea2ac#egg=ansys_dpf_composites
ansys-dpf-core==0.5.2
ansys-dpf-gate==0.2.1
ansys-dpf-gatebin==0.2.1
ansys-grpc-dpf==0.6.0
ansys-sphinx-theme==0.4.2
appdirs==1.4.4
async-timeout==4.0.2
asynctest==0.13.0
attrs==22.1.0
Babel==2.10.3
beautifulsoup4==4.11.1
bleach==5.0.1
build==0.8.0
cachetools==5.2.0
certifi==2022.9.24
cfgv==3.3.1
charset-normalizer==2.1.1
colorama==0.4.5
commonmark==0.9.1
coverage==6.5.0
cycler==0.11.0
distlib==0.3.6
docutils==0.19
filelock==3.8.0
fonttools==4.37.3
frozenlist==1.3.1
google-api-core==2.10.1
google-api-python-client==2.63.0
google-auth==2.12.0
google-auth-httplib2==0.1.0
googleapis-common-protos==1.56.4
grpcio==1.49.1
httplib2==0.20.4
identify==2.5.5
idna==3.4
imageio==2.22.0
imagesize==1.4.1
importlib-metadata==4.12.0
iniconfig==1.1.1
jaraco.classes==3.2.3
Jinja2==3.1.2
keyring==23.9.3
kiwisolver==1.4.4
MarkupSafe==2.1.1
matplotlib==3.5.3
more-itertools==8.14.0
multidict==6.0.2
mypy==0.931
mypy-extensions==0.4.3
nodeenv==1.7.0
numpy==1.21.6
numpydoc==1.4.0
packaging==21.3
pep517==0.13.0
Pillow==9.2.0
pkginfo==1.8.3
platformdirs==2.5.2
pluggy==1.0.0
pre-commit==2.20.0
protobuf==3.20.1
psutil==5.9.2
py==1.11.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pydata-sphinx-theme==0.9.0
Pygments==2.13.0
pypandoc==1.9
pyparsing==3.0.9
pytest==7.1.3
pytest-cov==3.0.0
python-dateutil==2.8.2
pytz==2022.2.1
pyvista==0.36.1
pywin32-ctypes==0.2.0
PyYAML==6.0
readme-renderer==37.2
requests==2.28.1
requests-toolbelt==0.9.1
rfc3986==2.0.0
rich==12.5.1
rsa==4.9
typing_extensions==4.3.0
uritemplate==4.1.1
urllib3==1.26.12
virtualenv==20.16.5
vtk==9.2.0rc2
webencodings==0.5.1
wslink==1.8.2
yarl==1.8.1
zipp==3.8.1

**Comment by PProfizi** [comment]
Hi @janvonrickenbach, I've managed to reproduce using the package versions listed on Ansys 2022 R2.

I tried with updated packages (ansys-dpf-core==0.6.2, ansys-dpf-gate==0.2.3, ansys-dpf-gatebin==0.2.3, ansys_grpc_dpf==0.6.0) on Ansys 2022 R2 and it seemed to fix the problem.

**Comment by janvonrickenbach** [comment]
Indeed this bug is fixed in the latest version. Thanks!
