### ISSUE TITLE
manual start dpf server in Linux

### ISSUE THREAD

**Issue by xiepei1** [pyansys/pydpf-core#65]
```python

dpf.start_local_server(ansys_path="/share/hpc_apps//ansys/2021R2/v212/")


/tp/IntelCompiler/2019.3.199/linx64/lib/intel64:/tp/IntelMKL/2020.0.166/linx64/lib/intel64:/Framework/bin/Linux64:/commonfiles/fluids/lib/linx64:/aisol/dll/linx64:/aisol/lib/linx64:/tp/openssl/1.1.1j/linx64/lib:/aisol/bin/linx64:

ERROR: ld.so: object '/tp/IntelCompiler/2019.3.199/linx64/lib/intel64/libiomp5.so' from LD_PRELOAD cannot be preloaded: ignored.

ERROR: ld.so: object '/tp/IntelMKL/2020.0.166/linx64/lib/intel64/libmkl_core.so' from LD_PRELOAD cannot be preloaded: ignored.

ERROR: ld.so: object '/tp/IntelMKL/2020.0.166/linx64/lib/intel64/libmkl_gnu_thread.so' from LD_PRELOAD cannot be preloaded: ignored.

terminate called after throwing an instance of 'std::runtime_error'

  what():  Impossible to load libDataProcessingCore.so. Error is "libDataProcessingCore.so: cannot open shared object file: No such file or directory"

./Ans.Dpf.Grpc.sh: line 9: 38421 Aborted                 ./Ans.Dpf.Grpc.exe $*

Traceback (most recent call last):

  File "<ipython-input-7-0338e76e16a0>", line 1, in <module>
    dpf.start_local_server(ansys_path="/share/hpc_apps//ansys/2021R2/v212/")

  File "/home/user/.conda/envs/pyansys/lib/python3.7/site-packages/ansys/dpf/core/server.py", line 177, in start_local_server
    server = DpfServer(ansys_path, ip, port,as_global= as_global, load_operators = load_operators)

  File "/home/user/.conda/envs/pyansys/lib/python3.7/site-packages/ansys/dpf/core/server.py", line 281, in __init__
    launch_dpf(ansys_path, ip, port)

  File "/home/user/.conda/envs/pyansys/lib/python3.7/site-packages/ansys/dpf/core/server.py", line 502, in launch_dpf
    raise TimeoutError(f'Server did not start in {timeout} seconds')

TimeoutError: Server did not start in 10 seconds

```

tried to start manually the dpf server, cannot start due ansys installation path, with customized path in Linux `/share/hpc_apps//ansys/2021R2/v212/` <-- seemingly to be the right path level, if with `/share/hpc_apps//ansys/2021R2/` or deeper path, would be some other wrong msg.

with this, it returned with some error information about IntelMKL.... not so sure what exactly went wrong, should be something required for system? or it is because bad configuration of dpf?

**Comment by anslpa** [comment]
Hi @xiepei1, 

It may be because the AWP_ROOT212 environment variable needs to be set in your Linux environment. Could you please try to set it using "export AWP_ROOT212=/share/hpc_apps//ansys/2021R2/v212/", then rerun the mentioned python code ? 

If this fixes the issue, I think we may consider to set the AWP_ROOT212 variable in the python method "start_local_server" while the ansys_path argument is used (@rlagha , @cbellot000). 

Thank you

**Comment by xiepei1** [comment]
> Hi @xiepei1,
> 
> It may be because the `AWP_ROOT212 `environment variable needs to be set in your Linux environment. Could you please try to set it using `export AWP_ROOT212=/share/hpc_apps//ansys/2021R2/v212/`, then rerun the mentioned python code ?
> 
> If this fixes the issue, I think we may consider to set the AWP_ROOT212 variable in the python method "start_local_server" while the ansys_path argument is used (@rlagha , @cbellot000).
> 
> Thank you

Hello @anslpa , 

it does help fix the issue, it should help if the documentation also includes such configurations for other usrs.
