### ISSUE TITLE
CI release fails due to new example

### ISSUE THREAD

**Issue by PProfizi** [pyansys/pydpf-core#776]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

The development CI tests pydpf-core against the development version of the DPF server.
The release CI however, tests whether pydpf-core can be released at any time, and tests against the last released DPF server.

A problem arises when an example (or a test), using new operators available only in the dev DPF server, is merged into the master branch.
The release CI understandably fails, since the example is not flagged in any manner as requiring a minimal DPF server version.

To prevent us from having to filter PRs and make them wait, we need a way to flag examples with a minimal required DPF Server version, and to add the logic in the CI to not run those if the server version is too low.

This would also increase visibility for each example on what version the feature starts being available with.
A note, or a warning, should be added to new (every?) examples.   

### Steps To Reproduce

https://github.com/pyansys/pydpf-core/actions/runs/4036910763/jobs/6939844493#step:8:2350

### Which Operating System are you using?

Windows

### Which DPF/Ansys version are you using?

DPF Server as standalone

### Which Python version are you using?

3.7

### Installed packages

https://github.com/pyansys/pydpf-core/actions/runs/4036910763/jobs/6939844493#step:7:21

**Comment by PProfizi** [comment]
@cbellot000 @anslpa @rafacanton any opinion on this?

**Comment by rafacanton** [comment]
> To prevent us from having to filter PRs and make them wait, we need a way to flag examples with a minimal required DPF Server version, and to add the logic in the CI to not run those if the server version is too low.

I think we already do something similar: look at line [7](https://github.com/pyansys/pydpf-core/blob/master/tests/test_lsdyna.py). We would need similar conftests for individual server versions, right?

**Comment by PProfizi** [comment]
> > To prevent us from having to filter PRs and make them wait, we need a way to flag examples with a minimal required DPF Server version, and to add the logic in the CI to not run those if the server version is too low.
> 
> I think we already do something similar: look at line [7](https://github.com/pyansys/pydpf-core/blob/master/tests/test_lsdyna.py). We would need similar conftests for individual server versions, right?

Yes, that is what we do for tests. For examples however, this logic does not exist yet, and I think we could find a way to make this transparent for the user (aka not putting ifs in the example's code). I think adding a Note mentioning a minimal version, and then the script running the examples would parse this note if it exists, and skip the example if necessary.
It would be both [here](https://github.com/pyansys/pydpf-core/blob/master/.ci/run_examples.py) and [here](https://github.com/pyansys/pydpf-core/blob/master/docs/source/conf.py) due to Sphinx gallery.
