### ISSUE TITLE
pyansys & discovery live

### ISSUE THREAD

**Issue by seghier** [pyansys/pydpf-core#91]
Hello
Can we use pyansys with discovery live ?

**Comment by akaszynski** [comment]
> Can we use pyansys with discovery live ?

Good question, and it's helpful to have these questions here.

Sadly, not at the moment.

I can't make any promises regarding a future Python library for Discovery Live, but I think one would be really helpful.  I'll be sure to forward this to the appropriate channels.

**Comment by JulienClinNuma** [comment]
Great suggestion @seghier!
We ambition in the future to develop dedicated apps based on the discovery live simulation engine and that would be of great help @akaszynski
